<?php

/**
 * @file
 * Searchsense un/installtion hooks.
 */

/**
 * Implements hook_install().
 */
function searchsense_install() {
  drupal_set_message(st('Searchsense has been installed. You can configure it in the <a href="!link">search autocomplete settings</a>.',
    array('!link' => url('admin/settings/search/autocomplete'))
  ));
}

/**
 * Implements hook_uninstall().
 */
function searchsense_uninstall() {
  variable_del('searchsense_configs');
  variable_del('searchsense_js_deps');
}

