<?php

/**
 * @file
 * Implementation of Searchsense API and other hooks.
 *
 * @todo
 * - Use selective vocabularies.
 * - Custom suggestion entry prefix and suffix.
 */

/**
 * Implements hook_searchsense.
 */
function taxosense_searchsense($a1 = '', $a2 = '', $limit = 10) {
  $matches = $args = array();
  if (!$a1) {
    return $matches;
  }

  // Get query template.
  $query = variable_get('taxosense_query', FALSE);
  if (!$query) {
    return $matches;
  }
  // Replace query placeholders.
  $args = array_fill(0, substr_count($query, '%s'), db_escape_string($a1));
  // Query and walk through the results.
  $results = db_query_range($query, $args, 0, (int) $limit);
  // Set entries prefix.
  $prefix = variable_get('taxosense_prefix', FALSE);
  $prefix = $prefix ? $prefix . ' ' : '';
  // Set entries suffix.
  $suffix = variable_get('taxosense_suffix', FALSE);
  $suffix = $suffix ? ' ' . $suffix : '';
  // Build the matches array.
  while ($result = db_fetch_object($results)) {
    $matches[$result->name] = check_plain($prefix . $result->name . $suffix);
  }

  return array('taxosense' => $matches);
}

/**
 * Implements hook_form_searchsense_admin_alter().
 */
function taxosense_form_searchsense_admin_alter(&$form, $form_state) {
  $options = variable_get('taxosense_options', array('term name', 'left match'));

  $form['taxosense'] = array(
    '#type' => 'fieldset',
    '#title' => t('Taxonomy Suggestions'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => 2,
  );

  $form['taxosense']['taxosense_options'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Choose appropriate taxonomy related suggestion options'),
    '#default_value' => $options,
    '#options' => array(
      'term name' => t('Suggest taxonomy term names.'),
      'term synonyms' => t('Suggest taxonomy term synonyms.'),
      'term description' => t('Suggest taxonomy terms with related descriptions.'),
      'left match' => t('Just <em>left match</em> to find suggestions.'),
    ),
  );

  $form['taxosense']['extra'] = array(
    '#type' => 'fieldset',
    '#title' => t('Extra Options'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['taxosense']['extra']['taxosense_prefix'] = array(
    '#type' => 'textfield',
    '#title' => t('Suggestion prefix'),
    '#description' => t('e.g. <em>Show all</em>'),
    '#default_value' => variable_get('taxosense_prefix', ''),
  );

  $form['taxosense']['extra']['taxosense_suffix'] = array(
    '#type' => 'textfield',
    '#title' => t('Suggestion suffix'),
    '#description' => t('e.g. <em>nodes</em>'),
    '#default_value' => variable_get('taxosense_suffix', ''),
  );

  $form['#submit'][] = 'taxosense_admin_submit';
}

/**
 * Submission callback for taxosense admin settings.
 */
function taxosense_admin_submit($form, &$form_state) {
  // Save options.
  variable_set('taxosense_options', $form_state['values']['taxosense_options']);

  // Build and save the query.
  $fields = 'name';
  $like = $form_state['values']['taxosense_options']['left match'] ? "'%s%%'" : "'%%%s%%'";
  $fields .= $form_state['values']['taxosense_options']['term description'] ? '' : '';
  $query = "(SELECT $fields FROM {term_data} t ";
  unset($fields);

  // Set the WHERE clause.
  $query .= "WHERE name LIKE $like";
  if ($form_state['values']['taxosense_options']['term description']) {
    $query .= " OR description LIKE $like";
  }
  $query .= ') ';

  // Include synonyms?
  if ($form_state['values']['taxosense_options']['term synonyms']) {
    $query .= "UNION (SELECT name FROM {term_synonym} WHERE name LIKE $like)";
  }

  variable_set('taxosense_query', $query);
  variable_set('taxosense_prefix', $form_state['values']['taxosense_prefix']);
  variable_set('taxosense_suffix', $form_state['values']['taxosense_suffix']);
}

